import Medicine from '../models/Medicine.js';

export const initialMedicines = [
  {
    name: 'Pantop 40',
    genericName: 'Pantoprazole',
    brandName: 'Pantop',
    companyName: 'Aristo Pharmaceuticals',
    supplierName: 'Parul Drug Distributors',
    group: 'Medicine',
    form: 'Tab.',
    strength: '40 mg',
    unit: 'Pcs',
    rateType: 'IC',
    rateIC: 5,
    rate: 8.0,
    quantity: 100,
    totalAmount: 800,
    stock: 250,
    minStockAlert: 20,
    stockStatus: 'In Stock',
    isNarcotics: false,
    discount: 0,
    description: 'Proton-pump inhibitor for acid reflux, GERD, and gastric ulcers.',
    status: 'published',
  },
  {
    name: 'Pantocid 40',
    genericName: 'Pantoprazole',
    brandName: 'Pantocid',
    companyName: 'Sun Pharma',
    supplierName: 'Shree Pharma Dist.',
    group: 'Medicine',
    form: 'Tab.',
    strength: '40 mg',
    unit: 'Strip',
    rateType: 'NC',
    rateIC: 0,
    rate: 150.0,
    quantity: 1,
    totalAmount: 150,
    stock: 85,
    minStockAlert: 15,
    stockStatus: 'In Stock',
    isNarcotics: false,
    discount: 5,
    description: 'Gastric acid secretion reducer.',
    status: 'published',
  },
  {
    name: 'Pansafe DSR',
    genericName: 'Pantoprazole + Domperidone',
    brandName: 'Pansafe DSR',
    companyName: 'Mankind Pharma',
    supplierName: 'Janakpur Medico',
    group: 'Medicine',
    form: 'Cap.',
    strength: '40 mg + 30 mg',
    unit: 'Strip',
    rateType: 'NC',
    rateIC: 0,
    rate: 195.0,
    quantity: 1,
    totalAmount: 195,
    stock: 6,
    minStockAlert: 10,
    stockStatus: 'Low Stock',
    isNarcotics: false,
    discount: 2,
    description: 'Dual action for acid reflux and associated nausea/vomiting.',
    status: 'published',
  },
  {
    name: 'Fortiplex Syrup',
    genericName: 'Vitamin B Complex with Zinc',
    brandName: 'Fortiplex',
    companyName: 'Apex Laboratories',
    supplierName: 'Parul Drug Distributors',
    group: 'Medicine',
    form: 'Syp.',
    strength: '200 ml',
    unit: 'Bottle',
    rateType: 'NC',
    rateIC: 0,
    rate: 165.0,
    quantity: 1,
    totalAmount: 165,
    stock: 45,
    minStockAlert: 10,
    stockStatus: 'In Stock',
    isNarcotics: false,
    discount: 0,
    description: 'High potency vitamin B complex supplement for nutritional support.',
    status: 'published',
  },
  {
    name: 'Polybion Active',
    genericName: 'Vitamin B Complex with B12',
    brandName: 'Polybion',
    companyName: 'Procter & Gamble Health',
    supplierName: 'Nepal Healthcare Dist.',
    group: 'Medicine',
    form: 'Syp.',
    strength: '300 ml',
    unit: 'Bottle',
    rateType: 'NC',
    rateIC: 0,
    rate: 210.0,
    quantity: 1,
    totalAmount: 210,
    stock: 0,
    minStockAlert: 5,
    stockStatus: 'Out of Stock',
    isNarcotics: false,
    discount: 0,
    description: 'Energy release and vitamin replenishment syrup.',
    status: 'published',
  },
  {
    name: 'Livoluk Syrup',
    genericName: 'Lactulose Solution USP',
    brandName: 'Livoluk',
    companyName: 'Panacea Biotec',
    supplierName: 'Shree Pharma Dist.',
    group: 'Medicine',
    form: 'Syp.',
    strength: '200 ml',
    unit: 'Bottle',
    rateType: 'NC',
    rateIC: 0,
    rate: 295.0,
    quantity: 1,
    totalAmount: 295,
    stock: 18,
    minStockAlert: 8,
    stockStatus: 'In Stock',
    isNarcotics: false,
    discount: 3,
    description: 'Osmotic laxative for constipation management and hepatic encephalopathy.',
    status: 'published',
  },
  {
    name: 'Smulac Syrup',
    genericName: 'Lactulose Oral Solution',
    brandName: 'Smulac',
    companyName: 'Macleods Pharma',
    supplierName: 'Parul Drug Distributors',
    group: 'Medicine',
    form: 'Syp.',
    strength: '100 ml',
    unit: 'Bottle',
    rateType: 'NC',
    rateIC: 0,
    rate: 180.0,
    quantity: 1,
    totalAmount: 180,
    stock: 4,
    minStockAlert: 10,
    stockStatus: 'Low Stock',
    isNarcotics: false,
    discount: 0,
    description: 'Gentle laxative syrup.',
    status: 'published',
  },
  {
    name: 'Sterilyte-NS (0.9% Normal Saline)',
    genericName: 'Sodium Chloride 0.9% w/v',
    brandName: 'Sterilyte-NS',
    companyName: 'Aculife Healthcare',
    supplierName: 'National Surgical House',
    group: 'Medicine',
    form: 'Ivf',
    strength: '500 ml',
    unit: 'Bottle',
    rateType: 'NC',
    rateIC: 0,
    rate: 75.0,
    quantity: 1,
    totalAmount: 75,
    stock: 120,
    minStockAlert: 25,
    stockStatus: 'In Stock',
    isNarcotics: false,
    discount: 0,
    description: 'Intravenous infusion solution for electrolyte and fluid replacement.',
    status: 'published',
  },
  {
    name: 'Centilink Surgical Blade #11',
    genericName: 'Carbon Steel Surgical Blade No. 11',
    brandName: 'Centilink Blades',
    companyName: 'Centilink Medtech',
    supplierName: 'National Surgical House',
    group: 'Surgical',
    form: 'Blade',
    strength: 'Size 11',
    unit: 'Box',
    rateType: 'NC',
    rateIC: 0,
    rate: 420.0,
    quantity: 1,
    totalAmount: 420,
    stock: 30,
    minStockAlert: 5,
    stockStatus: 'In Stock',
    isNarcotics: false,
    discount: 0,
    description: 'Sterile carbon steel surgical scalpel blades.',
    status: 'published',
  },
  {
    name: 'Surgicare Sterile Latex Surgical Gloves',
    genericName: 'Powder-free Surgical Gloves 7.5',
    brandName: 'Surgicare',
    companyName: 'Kanam Latex',
    supplierName: 'National Surgical House',
    group: 'Surgical',
    form: 'Gloves',
    strength: 'Size 7.5',
    unit: 'Box',
    rateType: 'NC',
    rateIC: 0,
    rate: 750.0,
    quantity: 1,
    totalAmount: 750,
    stock: 15,
    minStockAlert: 10,
    stockStatus: 'In Stock',
    isNarcotics: false,
    discount: 0,
    description: 'Latex surgical gloves with textured surface for high precision grip.',
    status: 'published',
  },
  {
    name: 'Foley Balloon Catheter 2-Way',
    genericName: 'Silicone Coated Latex Catheter 16 Fr',
    brandName: 'Romsons Foley',
    companyName: 'Romsons Group',
    supplierName: 'National Surgical House',
    group: 'Surgical',
    form: 'Catheter',
    strength: '16 Fr',
    unit: 'Pcs',
    rateType: 'NC',
    rateIC: 0,
    rate: 135.0,
    quantity: 1,
    totalAmount: 135,
    stock: 2,
    minStockAlert: 10,
    stockStatus: 'Low Stock',
    isNarcotics: false,
    discount: 0,
    description: 'Smooth silicone coated 2-way catheter for urinary drainage.',
    status: 'published',
  },
  {
    name: 'Nestle Cerelac Wheat & Apple',
    genericName: 'Infant Cereal Food',
    brandName: 'Cerelac',
    companyName: 'Nestle Nepal',
    supplierName: 'Central FMCG Stores',
    group: 'Extra Item',
    form: 'NA',
    strength: '300 g',
    unit: 'Box',
    rateType: 'NC',
    rateIC: 0,
    rate: 380.0,
    quantity: 1,
    totalAmount: 380,
    stock: 40,
    minStockAlert: 5,
    stockStatus: 'In Stock',
    isNarcotics: false,
    discount: 0,
    description: 'Nutritious fortified baby cereal for stage 1 infants.',
    status: 'published',
  },
];

export async function seedMedicines() {
  const count = await Medicine.countDocuments();
  if (count === 0) {
    console.log('Seeding initial hospital medicine inventory...');
    await Medicine.insertMany(initialMedicines);
    console.log(`Seeded ${initialMedicines.length} medicines successfully.`);
    return true;
  }
  return false;
}
