import type { LucideIcon } from 'lucide-react';
import {
  LayoutDashboard,
  Settings,
  Home,
  Building2,
  Stethoscope,
  Hospital,
  Layers,
  Images,
  MessageSquareQuote,
  Newspaper,
  CalendarDays,
  Package,
  Briefcase,
  CalendarCheck2,
  Inbox,
  HelpCircle,
  Download,
  ShieldCheck,
  Handshake,
  Megaphone,
  Search,
  FolderOpen,
  Info,
  Users,
  FileText,
} from 'lucide-react';

export type FieldType =
  | 'text'
  | 'textarea'
  | 'richtext'
  | 'number'
  | 'select'
  | 'toggle'
  | 'image'
  | 'file'
  | 'date'
  | 'tags'
  | 'status';

export type FieldConfig = {
  name: string;
  label: string;
  type: FieldType;
  required?: boolean;
  placeholder?: string;
  options?: { label: string; value: string }[];
  fullWidth?: boolean;
  rows?: number;
};

export type ModuleConfig = {
  key: string;
  path: string;
  label: string;
  singular: string;
  icon: LucideIcon;
  resource: string;
  description: string;
  group: 'overview' | 'content' | 'operations' | 'system';
  searchable?: boolean;
  statusFilter?: boolean;
  previewPath?: (item: any) => string | null;
  columns: { key: string; label: string; type?: 'text' | 'status' | 'image' | 'date' | 'badge' }[];
  fields: FieldConfig[];
  filters?: { key: string; label: string; options: { label: string; value: string }[] }[];
};

export const navGroups = [
  { key: 'overview', label: 'Overview' },
  { key: 'content', label: 'Website Content' },
  { key: 'operations', label: 'Operations' },
  { key: 'system', label: 'System' },
] as const;

export const modules: ModuleConfig[] = [
  {
    key: 'doctors',
    path: 'doctors',
    label: 'Doctors',
    singular: 'Doctor',
    icon: Stethoscope,
    resource: 'doctors',
    description: 'Manage doctors, specialists, and medical profiles.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    previewPath: (item) => (item?.slug ? `/appointment` : null),
    columns: [
      { key: 'imageUrl', label: 'Photo', type: 'image' },
      { key: 'name', label: 'Name' },
      { key: 'specialty', label: 'Specialty' },
      { key: 'category', label: 'Department', type: 'badge' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    filters: [
      {
        key: 'teamCategory',
        label: 'Team',
        options: [
          { label: 'Doctor', value: 'DOCTOR' },
        ],
      },
    ],
    fields: [
      { name: 'name', label: 'Full Name (English)', type: 'text', required: true },
      { name: 'nameNp', label: 'पूरा नाम (नेपाली)', type: 'text', required: true },
      { name: 'specialty', label: 'Specialty / Title (English)', type: 'text', required: true },
      { name: 'specialtyNp', label: 'विशेषज्ञता / पद (नेपाली)', type: 'text', required: true },
      { name: 'category', label: 'Department Category', type: 'text' },
      {
        name: 'teamCategory',
        label: 'Team Category',
        type: 'select',
        options: [
          { label: 'Doctor', value: 'DOCTOR' },
        ],
      },
      { name: 'qualification', label: 'Qualification (English)', type: 'text' },
      { name: 'qualificationNp', label: 'योग्यता (नेपाली)', type: 'text' },
      { name: 'specialization', label: 'Specialization (English)', type: 'text' },
      { name: 'specializationNp', label: 'विशिष्टता (नेपाली)', type: 'text' },
      { name: 'nmcNo', label: 'NMC No', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'imageUrl', label: 'Profile Image', type: 'image' },
      { name: 'bio', label: 'Biography (English)', type: 'richtext', fullWidth: true },
      { name: 'bioNp', label: 'जीवनी (नेपाली)', type: 'richtext', fullWidth: true },
      { name: 'isFeaturedOnHero', label: 'Featured on Hero', type: 'toggle' },
      { name: 'isBookable', label: 'Bookable', type: 'toggle' },
      { name: 'status', label: 'Status', type: 'status' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
    ],
  },
  {
    key: 'staff',
    path: 'staff',
    label: 'Staff',
    singular: 'Staff Member',
    icon: Users,
    resource: 'staff',
    description: 'Manage nursing, pharmacy, paramedical, radio imaging, and laboratory staff profiles.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    columns: [
      { key: 'imageUrl', label: 'Photo', type: 'image' },
      { key: 'name', label: 'Name' },
      { key: 'specialty', label: 'Title / Role' },
      { key: 'teamCategory', label: 'Staff Category', type: 'badge' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    filters: [
      {
        key: 'teamCategory',
        label: 'Staff Category',
        options: [
          { label: 'Nursing Staff', value: 'NURSING STAFF' },
          { label: 'Paramedical Staff', value: 'PARAMEDICAL STAFF' },
          { label: 'Pharmacy Staff', value: 'PHARMACY STAFF' },
          { label: 'Radio Imaging Staff', value: 'RADIO IMAGING STAFF' },
          { label: 'Laboratory Staff', value: 'LABORATORY STAFF' },
          { label: 'Management', value: 'MANAGEMENT' },
          { label: 'Administration', value: 'ADMINISTRATION' },
        ],
      },
    ],
    fields: [
      { name: 'name', label: 'Full Name (English)', type: 'text', required: true },
      { name: 'nameNp', label: 'पूरा नाम (नेपाली)', type: 'text', required: true },
      { name: 'specialty', label: 'Specialty / Title (English)', type: 'text', required: true },
      { name: 'specialtyNp', label: 'विशेषज्ञता / पद (नेपाली)', type: 'text', required: true },
      { name: 'category', label: 'Specialization (e.g. Lab, Nursing)', type: 'text' },
      {
        name: 'teamCategory',
        label: 'Team Category',
        type: 'select',
        options: [
          { label: 'Nursing Staff', value: 'NURSING STAFF' },
          { label: 'Paramedical Staff', value: 'PARAMEDICAL STAFF' },
          { label: 'Pharmacy Staff', value: 'PHARMACY STAFF' },
          { label: 'Radio Imaging Staff', value: 'RADIO IMAGING STAFF' },
          { label: 'Laboratory Staff', value: 'LABORATORY STAFF' },
          { label: 'Management', value: 'MANAGEMENT' },
          { label: 'Administration', value: 'ADMINISTRATION' },
        ],
      },
      { name: 'qualification', label: 'Qualification (English)', type: 'text' },
      { name: 'qualificationNp', label: 'योग्यता (नेपाली)', type: 'text' },
      { name: 'specialization', label: 'Specialization (English)', type: 'text' },
      { name: 'specializationNp', label: 'विशिष्टता (नेपाली)', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'imageUrl', label: 'Profile Image', type: 'image' },
      { name: 'bio', label: 'Biography (English)', type: 'richtext', fullWidth: true },
      { name: 'bioNp', label: 'जीवनी (नेपाली)', type: 'richtext', fullWidth: true },
      { name: 'status', label: 'Status', type: 'status' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
    ],
  },
  {
    key: 'departments',
    path: 'departments',
    label: 'Departments',
    singular: 'Department',
    icon: Building2,
    resource: 'departments',
    description: 'Hospital departments and specialty units.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    previewPath: (item) => (item?.slug ? `/department/${item.slug}` : null),
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'slug', label: 'Slug' },
      { key: 'specialistCountLabel', label: 'Specialists' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    fields: [
      { name: 'title', label: 'Title (English)', type: 'text', required: true },
      { name: 'titleNp', label: 'शीर्षक (नेपाली)', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text' },
      { name: 'shortDesc', label: 'Short Description (English)', type: 'textarea', rows: 3 },
      { name: 'shortDescNp', label: 'छोटो विवरण (नेपाली)', type: 'textarea', rows: 3 },
      { name: 'longDescription', label: 'Full Description (English)', type: 'richtext', fullWidth: true },
      { name: 'longDescriptionNp', label: 'पूर्ण विवरण (नेपाली)', type: 'richtext', fullWidth: true },
      { name: 'imageUrl', label: 'Image', type: 'image' },
      { name: 'iconKey', label: 'Icon Key', type: 'text' },
      { name: 'colorTheme', label: 'Color Theme', type: 'text' },
      { name: 'specialistCountLabel', label: 'Specialist Count Label (English)', type: 'text' },
      { name: 'specialistCountLabelNp', label: 'विशेषज्ञ संख्या लेबल (नेपाली)', type: 'text' },
      { name: 'services', label: 'Services (English, comma separated)', type: 'tags', fullWidth: true },
      { name: 'servicesNp', label: 'सेवाहरू (नेपाली, अल्पविरामले छुट्याइएको)', type: 'tags', fullWidth: true },
      { name: 'status', label: 'Status', type: 'status' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
    ],
  },
  {
    key: 'services',
    path: 'services',
    label: 'Services',
    singular: 'Service',
    icon: Hospital,
    resource: 'services',
    description: 'Clinical and support services offered by the hospital.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    columns: [
      { key: 'imageUrl', label: 'Image', type: 'image' },
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category', type: 'badge' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    filters: [
      {
        key: 'category',
        label: 'Category',
        options: [
          { label: 'Emergency', value: 'Emergency' },
          { label: 'Diagnostics', value: 'Diagnostics' },
          { label: 'Support', value: 'Support' },
          { label: 'Clinical', value: 'Clinical' },
          { label: 'Other', value: 'Other' },
        ],
      },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text' },
      {
        name: 'category',
        label: 'Category',
        type: 'select',
        options: [
          { label: 'Emergency', value: 'Emergency' },
          { label: 'Diagnostics', value: 'Diagnostics' },
          { label: 'Support', value: 'Support' },
          { label: 'Clinical', value: 'Clinical' },
          { label: 'Other', value: 'Other' },
        ],
      },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3, fullWidth: true },
      { name: 'contentHtml', label: 'Detailed Content', type: 'richtext', fullWidth: true },
      { name: 'imageUrl', label: 'Image', type: 'image' },
      { name: 'iconKey', label: 'Icon Key', type: 'text' },
      { name: 'hideRequestAppointment', label: 'Hide Appointment CTA', type: 'toggle' },
      { name: 'status', label: 'Status', type: 'status' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
    ],
  },
  {
    key: 'facilities',
    path: 'facilities',
    label: 'Facilities',
    singular: 'Facility',
    icon: Layers,
    resource: 'facilities',
    description: 'Hospital facilities and infrastructure highlights.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    columns: [
      { key: 'imageUrl', label: 'Image', type: 'image' },
      { key: 'title', label: 'Title' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3, fullWidth: true },
      { name: 'contentHtml', label: 'Details', type: 'richtext', fullWidth: true },
      { name: 'imageUrl', label: 'Image', type: 'image' },
      { name: 'iconKey', label: 'Icon Key', type: 'text' },
      { name: 'status', label: 'Status', type: 'status' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
    ],
  },
  {
    key: 'gallery',
    path: 'gallery',
    label: 'Gallery',
    singular: 'Gallery Item',
    icon: Images,
    resource: 'gallery',
    description: 'Photo and video gallery collections.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    previewPath: () => '/gallery',
    columns: [
      { key: 'url', label: 'Media', type: 'image' },
      { key: 'title', label: 'Title' },
      { key: 'album', label: 'Album', type: 'badge' },
      { key: 'type', label: 'Type', type: 'badge' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    filters: [
      {
        key: 'album',
        label: 'Album',
        options: [
          { label: 'Hospital', value: 'hospital' },
          { label: 'Academic', value: 'academic' },
          { label: 'Event', value: 'event' },
          { label: 'Other', value: 'other' },
        ],
      },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      {
        name: 'type',
        label: 'Type',
        type: 'select',
        options: [
          { label: 'Photo', value: 'photo' },
          { label: 'Video', value: 'video' },
        ],
      },
      {
        name: 'album',
        label: 'Album',
        type: 'select',
        options: [
          { label: 'Hospital', value: 'hospital' },
          { label: 'Academic', value: 'academic' },
          { label: 'Event', value: 'event' },
          { label: 'Other', value: 'other' },
        ],
      },
      { name: 'url', label: 'Image / Media URL', type: 'image', required: true },
      { name: 'videoUrl', label: 'Video URL', type: 'text' },
      { name: 'thumbnailUrl', label: 'Thumbnail', type: 'image' },
      { name: 'duration', label: 'Duration', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3, fullWidth: true },
      { name: 'status', label: 'Status', type: 'status' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
    ],
  },
  {
    key: 'testimonials',
    path: 'testimonials',
    label: 'Testimonials',
    singular: 'Testimonial',
    icon: MessageSquareQuote,
    resource: 'testimonials',
    description: 'Patient stories and reviews.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'role', label: 'Role' },
      { key: 'rating', label: 'Rating' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'role', label: 'Role', type: 'text' },
      { name: 'content', label: 'Testimonial', type: 'richtext', required: true, fullWidth: true },
      { name: 'rating', label: 'Rating (1-5)', type: 'number' },
      { name: 'imageUrl', label: 'Photo', type: 'image' },
      { name: 'isFeatured', label: 'Featured', type: 'toggle' },
      { name: 'status', label: 'Status', type: 'status' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
    ],
  },
  {
    key: 'blogs',
    path: 'blogs',
    label: 'Blogs & News',
    singular: 'Blog',
    icon: Newspaper,
    resource: 'blogs',
    description: 'Health tips, blogs, and articles.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    previewPath: (item) => (item?.slug || item?._id ? `/blog/${item.slug || item._id}` : '/blogs'),
    columns: [
      { key: 'imageUrl', label: 'Image', type: 'image' },
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category', type: 'badge' },
      { key: 'author', label: 'Author' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text' },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'author', label: 'Author', type: 'text' },
      { name: 'date', label: 'Publish Date', type: 'date' },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea', rows: 3, fullWidth: true },
      { name: 'description', label: 'Short Description', type: 'textarea', rows: 3, fullWidth: true },
      { name: 'fullContent', label: 'Full Content', type: 'richtext', fullWidth: true },
      { name: 'imageUrl', label: 'Cover Image', type: 'image' },
      { name: 'iconKey', label: 'Icon Key', type: 'text' },
      { name: 'tags', label: 'Tags', type: 'tags', fullWidth: true },
      { name: 'status', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'events',
    path: 'events',
    label: 'Events',
    singular: 'Event',
    icon: CalendarDays,
    resource: 'events',
    description: 'News, events, notices, and academic updates.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    previewPath: (item) => (item?._id ? `/news/${item._id}` : '/news-events'),
    columns: [
      { key: 'imageUrl', label: 'Image', type: 'image' },
      { key: 'title', label: 'Title' },
      { key: 'type', label: 'Type', type: 'badge' },
      { key: 'category', label: 'Category', type: 'badge' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    filters: [
      {
        key: 'category',
        label: 'Category',
        options: [
          { label: 'News', value: 'News' },
          { label: 'Event', value: 'Event' },
          { label: 'Notice', value: 'Notice' },
          { label: 'Academic', value: 'Academic' },
          { label: 'Strategic', value: 'Strategic' },
        ],
      },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text' },
      {
        name: 'type',
        label: 'Type',
        type: 'select',
        options: [
          { label: 'News', value: 'News' },
          { label: 'Event', value: 'Event' },
          { label: 'Notice', value: 'Notice' },
          { label: 'Result', value: 'Result' },
          { label: 'Admission', value: 'Admission' },
          { label: 'Scholarship', value: 'Scholarship' },
          { label: 'Academic', value: 'Academic' },
          { label: 'Strategic', value: 'Strategic' },
        ],
      },
      {
        name: 'category',
        label: 'Category',
        type: 'select',
        options: [
          { label: 'News', value: 'News' },
          { label: 'Event', value: 'Event' },
          { label: 'Notice', value: 'Notice' },
          { label: 'Academic', value: 'Academic' },
          { label: 'Strategic', value: 'Strategic' },
        ],
      },
      { name: 'date', label: 'Date', type: 'date' },
      { name: 'time', label: 'Time', type: 'text' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3, fullWidth: true },
      { name: 'fullContent', label: 'Full Content', type: 'richtext', fullWidth: true },
      { name: 'imageUrl', label: 'Image', type: 'image' },
      { name: 'isSpecial', label: 'Special Highlight', type: 'toggle' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'health-packages',
    path: 'health-packages',
    label: 'Health Packages',
    singular: 'Package',
    icon: Package,
    resource: 'health-packages',
    description: 'Health checkup and wellness packages.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'price', label: 'Price' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text' },
      { name: 'price', label: 'Price', type: 'number' },
      { name: 'currency', label: 'Currency', type: 'text' },
      { name: 'duration', label: 'Duration', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3, fullWidth: true },
      { name: 'contentHtml', label: 'Details', type: 'richtext', fullWidth: true },
      { name: 'features', label: 'Features', type: 'tags', fullWidth: true },
      { name: 'imageUrl', label: 'Image', type: 'image' },
      { name: 'isPopular', label: 'Popular', type: 'toggle' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'careers',
    path: 'careers',
    label: 'Careers',
    singular: 'Job',
    icon: Briefcase,
    resource: 'careers',
    description: 'Job openings and career opportunities.',
    group: 'operations',
    searchable: true,
    statusFilter: true,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'department', label: 'Department' },
      { key: 'employmentType', label: 'Type', type: 'badge' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    fields: [
      { name: 'title', label: 'Job Title', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'text' },
      { name: 'location', label: 'Location', type: 'text' },
      {
        name: 'employmentType',
        label: 'Employment Type',
        type: 'select',
        options: [
          { label: 'Full-time', value: 'Full-time' },
          { label: 'Part-time', value: 'Part-time' },
          { label: 'Contract', value: 'Contract' },
          { label: 'Internship', value: 'Internship' },
        ],
      },
      { name: 'vacancies', label: 'Vacancies', type: 'number' },
      { name: 'deadline', label: 'Deadline', type: 'date' },
      { name: 'description', label: 'Description', type: 'richtext', fullWidth: true },
      { name: 'requirementsHtml', label: 'Requirements', type: 'richtext', fullWidth: true },
      { name: 'responsibilitiesHtml', label: 'Responsibilities', type: 'richtext', fullWidth: true },
      { name: 'status', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'appointments',
    path: 'appointments',
    label: 'Appointments',
    singular: 'Appointment',
    icon: CalendarCheck2,
    resource: 'appointments',
    description: 'Incoming appointment requests from the website.',
    group: 'operations',
    searchable: true,
    statusFilter: false,
    columns: [
      { key: 'patientName', label: 'Patient' },
      { key: 'phone', label: 'Phone' },
      { key: 'doctor', label: 'Doctor' },
      { key: 'department', label: 'Department' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    filters: [
      {
        key: 'status',
        label: 'Status',
        options: [
          { label: 'Pending', value: 'pending' },
          { label: 'Confirmed', value: 'confirmed' },
          { label: 'Cancelled', value: 'cancelled' },
          { label: 'Completed', value: 'completed' },
        ],
      },
    ],
    fields: [
      { name: 'patientName', label: 'Patient Name', type: 'text', required: true },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'doctor', label: 'Doctor', type: 'text' },
      { name: 'department', label: 'Department', type: 'text' },
      { name: 'appointmentDate', label: 'Appointment Date', type: 'date' },
      { name: 'shift', label: 'Shift', type: 'text' },
      { name: 'message', label: 'Message', type: 'textarea', rows: 4, fullWidth: true },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Pending', value: 'pending' },
          { label: 'Confirmed', value: 'confirmed' },
          { label: 'Cancelled', value: 'cancelled' },
          { label: 'Completed', value: 'completed' },
        ],
      },
      { name: 'notes', label: 'Internal Notes', type: 'textarea', rows: 3, fullWidth: true },
    ],
  },
  {
    key: 'enquiries',
    path: 'enquiries',
    label: 'Contact Enquiries',
    singular: 'Enquiry',
    icon: Inbox,
    resource: 'enquiries',
    description: 'Contact form and inquiry submissions.',
    group: 'operations',
    searchable: true,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'phone', label: 'Phone' },
      { key: 'subject', label: 'Subject' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    filters: [
      {
        key: 'status',
        label: 'Status',
        options: [
          { label: 'New', value: 'new' },
          { label: 'In Progress', value: 'in_progress' },
          { label: 'Resolved', value: 'resolved' },
          { label: 'Archived', value: 'archived' },
        ],
      },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'subject', label: 'Subject', type: 'text' },
      { name: 'message', label: 'Message', type: 'textarea', rows: 5, fullWidth: true },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'New', value: 'new' },
          { label: 'In Progress', value: 'in_progress' },
          { label: 'Resolved', value: 'resolved' },
          { label: 'Archived', value: 'archived' },
        ],
      },
      { name: 'notes', label: 'Internal Notes', type: 'textarea', rows: 3, fullWidth: true },
    ],
  },
  {
    key: 'faqs',
    path: 'faqs',
    label: 'FAQs',
    singular: 'FAQ',
    icon: HelpCircle,
    resource: 'faqs',
    description: 'Frequently asked questions.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    columns: [
      { key: 'question', label: 'Question' },
      { key: 'category', label: 'Category', type: 'badge' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    fields: [
      { name: 'question', label: 'Question', type: 'text', required: true, fullWidth: true },
      { name: 'answer', label: 'Answer', type: 'richtext', required: true, fullWidth: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'status', label: 'Status', type: 'status' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
    ],
  },
  {
    key: 'downloads',
    path: 'downloads',
    label: 'Downloads',
    singular: 'Download',
    icon: Download,
    resource: 'downloads',
    description: 'Downloadable documents and brochures.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    previewPath: () => '/downloads',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'type', label: 'Type', type: 'badge' },
      { key: 'sizeLabel', label: 'Size' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'type', label: 'Type', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3, fullWidth: true },
      { name: 'fileUrl', label: 'File', type: 'file', required: true },
      { name: 'filename', label: 'Filename', type: 'text' },
      { name: 'sizeLabel', label: 'Size Label', type: 'text' },
      { name: 'iconKey', label: 'Icon Key', type: 'text' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'insurance',
    path: 'insurance',
    label: 'Insurance Partners',
    singular: 'Insurance',
    icon: ShieldCheck,
    resource: 'insurance',
    description: 'Accepted insurance providers.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    columns: [
      { key: 'logoUrl', label: 'Logo', type: 'image' },
      { key: 'name', label: 'Name' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'logoUrl', label: 'Logo', type: 'image' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3, fullWidth: true },
      { name: 'coverageDetails', label: 'Coverage Details', type: 'richtext', fullWidth: true },
      { name: 'websiteUrl', label: 'Website', type: 'text' },
      { name: 'contactPhone', label: 'Contact Phone', type: 'text' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'partners',
    path: 'partners',
    label: 'Hospital Partners',
    singular: 'Partner',
    icon: Handshake,
    resource: 'partners',
    description: 'Partner organizations and affiliations.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    columns: [
      { key: 'logoUrl', label: 'Logo', type: 'image' },
      { key: 'name', label: 'Name' },
      { key: 'type', label: 'Type', type: 'badge' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'type', label: 'Type', type: 'text' },
      { name: 'logoUrl', label: 'Logo', type: 'image' },
      { name: 'websiteUrl', label: 'Website', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3, fullWidth: true },
      { name: 'status', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'announcements',
    path: 'announcements',
    label: 'Announcements',
    singular: 'Announcement',
    icon: Megaphone,
    resource: 'announcements',
    description: 'Marquee and site-wide announcements.',
    group: 'content',
    searchable: true,
    statusFilter: true,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'type', label: 'Type', type: 'badge' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'content', label: 'Content', type: 'richtext', fullWidth: true },
      {
        name: 'type',
        label: 'Type',
        type: 'select',
        options: [
          { label: 'Info', value: 'info' },
          { label: 'Warning', value: 'warning' },
          { label: 'Success', value: 'success' },
          { label: 'Urgent', value: 'urgent' },
        ],
      },
      { name: 'linkUrl', label: 'Link URL', type: 'text' },
      { name: 'startsAt', label: 'Starts At', type: 'date' },
      { name: 'endsAt', label: 'Ends At', type: 'date' },
      { name: 'showOnMarquee', label: 'Show on Marquee', type: 'toggle' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'seo',
    path: 'seo',
    label: 'SEO Settings',
    singular: 'SEO Page',
    icon: Search,
    resource: 'seo',
    description: 'Per-page SEO titles, descriptions, and metadata.',
    group: 'system',
    searchable: true,
    columns: [
      { key: 'pageName', label: 'Page' },
      { key: 'title', label: 'SEO Title' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    fields: [
      { name: 'pageKey', label: 'Page Key', type: 'text', required: true },
      { name: 'pageName', label: 'Page Name', type: 'text', required: true },
      { name: 'title', label: 'Meta Title', type: 'text', fullWidth: true },
      { name: 'description', label: 'Meta Description', type: 'textarea', rows: 3, fullWidth: true },
      { name: 'keywords', label: 'Keywords', type: 'tags', fullWidth: true },
      { name: 'ogImage', label: 'OG Image', type: 'image' },
      { name: 'canonicalUrl', label: 'Canonical URL', type: 'text' },
      { name: 'noIndex', label: 'No Index', type: 'toggle' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
  },
  {
    key: 'patients',
    path: 'patients',
    label: 'Patients',
    singular: 'Patient',
    icon: Users,
    resource: 'patients',
    description: 'Manage patient accounts and login credentials.',
    group: 'system',
    searchable: true,
    columns: [
      { key: 'username', label: 'Patient ID (Username)' },
      { key: 'name', label: 'Name' },
      { key: 'phone', label: 'Phone' },
      { key: 'updatedAt', label: 'Last Updated', type: 'date' },
    ],
    fields: [
      { name: 'name', label: 'Full Name', type: 'text', required: true },
      { name: 'username', label: 'Patient ID (Username)', type: 'text', required: true },
      { name: 'password', label: 'Password (Plain text to show on slips)', type: 'text', required: true },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
    ],
  },
  {
    key: 'labreports',
    path: 'labreports',
    label: 'Lab Reports',
    singular: 'Lab Report',
    icon: FileText,
    resource: 'labreports',
    description: 'Upload and manage patient medical reports.',
    group: 'system',
    searchable: true,
    columns: [
      { key: 'patientUsername', label: 'Patient ID' },
      { key: 'testName', label: 'Test Name' },
      { key: 'testDate', label: 'Test Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    fields: [
      { name: 'patientUsername', label: 'Patient ID (Username)', type: 'text', required: true },
      { name: 'testName', label: 'Test Name (English)', type: 'text', required: true },
      { name: 'testNameNp', label: 'Test Name (नेपाली)', type: 'text', required: true },
      { name: 'testDate', label: 'Test Date', type: 'date', required: true },
      {
        name: 'department',
        label: 'Department',
        type: 'select',
        options: [
          { label: 'Laboratory', value: 'Laboratory' },
          { label: 'Pathology', value: 'Pathology' },
          { label: 'Radiology', value: 'Radiology' },
          { label: 'Cardiology', value: 'Cardiology' },
        ],
      },
      {
        name: 'priority',
        label: 'Priority',
        type: 'select',
        options: [
          { label: 'Normal', value: 'Normal' },
          { label: 'Urgent', value: 'Urgent' },
        ],
      },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Ready', value: 'Ready' },
          { label: 'Processing', value: 'Processing' },
          { label: 'Draft', value: 'Draft' },
        ],
      },
      { name: 'pdfUrl', label: 'Upload PDF Report', type: 'file', required: true },
    ],
  },
];

export const specialNav = [
  { path: '', label: 'Dashboard', icon: LayoutDashboard, group: 'overview' as const },
  { path: 'settings', label: 'Website Settings', icon: Settings, group: 'system' as const },
  { path: 'homepage', label: 'Homepage', icon: Home, group: 'content' as const },
  { path: 'about', label: 'About Hospital', icon: Info, group: 'content' as const },
  { path: 'media', label: 'Media Library', icon: FolderOpen, group: 'system' as const },
];

export function getModule(path: string) {
  return modules.find((m) => m.path === path);
}
